---
title: "PS270 Final Project"
author: "Sam Swartz"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to comparing data in Wisconsin with other bordering states/the rest of the U.S. Maybe something about education or politics, etc.

## Research Question and Outline
Research Question: How does voter turnout affect the electoral success of Democratic candidates in Wisconsin state elections?

Hypothesis: Higher voter turnout is associated with a greater likelihood of Democratic candidates winning elections because traditionally underrepresented groups that lean Democratic, like younger voters, minorities, lower-income people, etc., are more likely to vote in higher-turnout elections. When turnout is low, the electorate tends to skew towards wealthier, older, and more conservative voters, which can favor Republican candidates.

Independent Variable: Voter turnout measured as the percentage of eligable voters who cast ballots.
Dependent Variable: Success of Democratic candidates measured as the percentage of the vote received by Democratic candidates/whether they win or lose.

Data That Would Support Hypothesis: Higher turnouts would be associated with better performance for Democratic candidates.
Data That Would Disprove Hypothesis: No clear relationship or higher turnout correlating with better performance for Republican candidates.


```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)

data <- read_csv('VoteData.csv')

data <- data |>
  dplyr::select(Year, `General Election Turnout`, Win) |>
  mutate(`General Election Turnout` = as.numeric(gsub("%", "", `General Election Turnout`)))

ggplot(data, aes(x = Year, y = `General Election Turnout`, fill = Win)) +
  geom_bar(stat = "identity") +
  labs(
    title = "General Election Turnout in Wisconsin in Presidential Election Years",
    subtitle  = "The percent of voter turnout in Wisconsin compared to the party candidate that won the state",
    x = "Year",
    y = "Turnout (%)",
    caption = "Source: Wisconsin Elections Commision"
  ) +
  scale_fill_manual(values = c("D" = "blue", "R" = "red")) +
  theme_minimal()

```


